### ISSUE TITLE
Can't parse in <code> tag md file

### ISSUE THREAD

**Issue by dulx96** [laysent/remark-ruby#1]
Im using gatsby newest version with gatsby-transformer-remark within plugin gatsby-remark-ruby
All h1,h2,..p, codeblock work well except <code> tag 

<code>  this is a code {紳士}^(へんたい) </code>

can any one give me a soluyion ? thanks

**Comment by laysent** [comment]
Hi @dulx96 , do you have a minimum configuration where I can test? I personally is also using `gatsby-remark-ruby` on my blog. It should work, at least in my case. Probably there are some cases where I am not aware of, more info will be very helpful.

**Comment by dulx96** [comment]
> Hi @dulx96 , when you use `` to produce code tag, I believe what's inside should be considered as plain text and should not be transformed. Example: `<p>html</p>`. Thus, plugin should not transform text inside.
> If you wish to have ruby inside code tag, I would recommend to write html directly. Example:
> 
> ```
> <code><ruby>紳士<rp>(</rp><rt>へんたい</rt><rp>)</rp></code>
> ```

thanks, u help me a lot
